"""add feedback to traces

Revision ID: b867ba01d328
Revises: 2541b8a95ab9
Create Date: 2026-06-25 21:29:15.162346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b867ba01d328'
down_revision: Union[str, None] = '2541b8a95ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_traces', sa.Column('feedback', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_traces', 'feedback')
    # ### end Alembic commands ###
